import assert from 'node:assert/strict';
import vm from 'node:vm';
import worker,{PriceHistory,activitySnapshot} from './worker-autotrading.js';
import panel from './owner-panel.mjs';
import {candles,signalDataHealth} from './worker-v450.js';
assert.equal(signalDataHealth({ticker:'T'},null,{btc:{latest:{p:80000}}},{ok:false,error:'Coinbase candles 429'}).reason,'Coinbase candles 429');
assert.equal(signalDataHealth({ticker:'T'},null,{btc:{}},{ok:true}).reason,'BTC price unavailable');
assert.equal(signalDataHealth({ticker:'T'},{side:null},{btc:{latest:{p:80000}}},{ok:true,candles:60}).available,true);
const map=new Map([['scalpLog',[{ticker:'OLD',entry:.5,exit:.6,contracts:9}]],['subs',[{endpoint:'preserved'}]]]);
const storage={get:async k=>structuredClone(map.get(k)),put:async(k,v)=>map.set(k,structuredClone(v)),delete:async k=>map.delete(k)};
const env={AUTO_TRADING_MODE:'disabled',AUTO_TRADING_OWNER_TOKEN:'x'.repeat(32)};const p=new PriceHistory({storage},env);env.PRICE_HISTORY={idFromName:x=>x,get:()=>({fetch:req=>p.fetch(typeof req==='string'?new Request(req):req)})};
const req=(path,method='GET',body,token)=>new Request('https://worker'+path,{method,headers:{...(token?{authorization:'Bearer '+token}:{}),'content-type':'application/json'},body:body?JSON.stringify(body):undefined});
const publicConfig=await worker.fetch(req('/api/auto/config'),env,{});assert.equal(publicConfig.headers.get('access-control-allow-origin'),'*');const cfg=await publicConfig.json();assert.equal(cfg.mode,'disabled');assert.equal(cfg.enabled,false);assert.equal(cfg.ownerTokenConfigured,true);assert(!('position' in cfg));assert(!('orders' in cfg));assert.equal((await worker.fetch(req('/api/auto/status'),env,{})).status,401);
assert.equal((await worker.fetch(req('/api/auto/control','POST',{action:'enable'}),env,{})).status,401);
for(const [token,expected] of [[undefined,'No owner token'],['short','shorter than 32'],['y'.repeat(32),'does not match']]){const response=await worker.fetch(req('/api/auto/status','GET',null,token),env,{});assert.equal(response.status,401);const failure=await response.json();assert(failure.detail.includes(expected));assert.equal(failure.stage,'worker');assert(!JSON.stringify(failure).includes(env.AUTO_TRADING_OWNER_TOKEN))}
const missing=await(await worker.fetch(req('/api/auto/status'),{...env,AUTO_TRADING_OWNER_TOKEN:undefined},{})).json();assert(missing.detail.includes('deployed owner secret is missing'));
const inner=await(await p.fetch(req('/auto/status','GET',null,'y'.repeat(32)))).json();assert.equal(inner.stage,'storage');assert(inner.detail.includes('does not match'));
const status=await(await worker.fetch(req('/api/auto/status','GET',null,env.AUTO_TRADING_OWNER_TOKEN),env,{})).json();assert.equal(status.enabled,false);assert.equal(status.mode,'disabled');assert.equal(status.rules.minScore,.9);assert.equal(status.build,cfg.build);assert.equal(status.connection.ok,false);assert.equal(status.connection.stage,'credentials');assert.equal(map.has('autoTrading:v1'),false);
p.autoEngine.broker.balance=async()=>{throw Object.assign(Error('mock signing failure'),{stage:'request signing'})};const diagnostic=await(await worker.fetch(req('/api/auto/status','GET',null,env.AUTO_TRADING_OWNER_TOKEN),env,{})).json();assert.equal(diagnostic.connection.stage,'request signing');assert.equal(diagnostic.enabled,false);assert.equal(map.has('autoTrading:v1'),false);
const failedEnable=await(await worker.fetch(req('/api/auto/control','POST',{action:'enable'},env.AUTO_TRADING_OWNER_TOKEN),env,{})).json();assert.equal(failedEnable.build,cfg.build);
assert.equal((await worker.fetch(req('/api/auto/control','POST',{action:'enable'},env.AUTO_TRADING_OWNER_TOKEN),env,{})).status,409);
map.set('autoTrading:v1',{enabled:false,paused:'Unresolved order',position:{ticker:'T',entryOrder:'CID'},seen:['T:NO'],history:[],orders:[{clientOrderId:'CID',state:'UNCERTAIN',error:'Kalshi POST HTTP 400',errorStage:'Kalshi response'}]});
p.autoEngine.broker.findClient=async()=>[];p.autoEngine.broker.position=async()=>0;p.autoEngine.broker.resting=async()=>[];p.autoEngine.broker.marketFills=async()=>[];
const snapshot=structuredClone([...map]);const pausedStatus=await(await worker.fetch(req('/api/auto/status','GET',null,env.AUTO_TRADING_OWNER_TOKEN),env,{})).json();assert.equal(pausedStatus.orderDiagnostics.readOnly,true);assert.equal(pausedStatus.orderDiagnostics.matchingOrderCount,0);assert.equal(pausedStatus.orderDiagnostics.submissionError,'Kalshi POST HTTP 400');assert.deepEqual([...map],snapshot);map.delete('autoTrading:v1');
const old=structuredClone(map.get('scalpLog'));await p.scalpPaper({ticker:'T',yes_bid:.5},null);assert.deepEqual(map.get('scalpLog'),old);assert.equal(map.get('subs')[0].endpoint,'preserved');
const page=await worker.fetch(req('/auto'),env,{});assert.equal(page.status,200);assert(page.headers.get('content-security-policy').includes("frame-ancestors 'none'"));
const script=panel.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);assert(!script.includes('localStorage'));assert(!script.includes('sessionStorage'));assert(!panel.includes(env.AUTO_TRADING_OWNER_TOKEN));
console.log('PASS: owner auth, disabled activation guard, rule status, preserved paper history/subscriptions, panel isolation and script syntax');

let featureReads=0;p.candleFeed.read=async()=>{featureReads++;return{ok:true,candles:60}};await p.fetch(req('/candle-features'));await p.fetch(req('/candle-features'));assert.equal(featureReads,1);
const paths=[];const routeEnv={PRICE_HISTORY:{idFromName:x=>x,get:()=>({fetch:async r=>{const q=typeof r==='string'?new Request(r):r,path=new URL(q.url).pathname;paths.push(path);if(path==='/market')return Response.json({status:'live',market:{ticker:'TEST',close_time:new Date(Date.now()+300000).toISOString(),yes_ask:50,no_ask:50}});if(path==='/snapshot')return Response.json({latest:{p:80000},points:[]});if(path==='/candle-features')return Response.json({ok:false,error:'mock 429',retryAt:123});if(path==='/scalp-tick'){const body=await q.json();assert.equal(body.features.error,'mock 429');assert.equal(body.scalp,null);return Response.json({ok:true})}throw Error(path)}})}};await worker.fetch(req('/api/current'),routeEnv,{});assert(paths.includes('/candle-features'));console.log('PASS: shared feature endpoint and public signal route use Durable Object cache');

const candleNow=1800000000000,rows=Array.from({length:60},(_,i)=>({start:String(candleNow/1000-(59-i)*60),low:'79990',high:'80010',open:'80000',close:String(80000+i),volume:'3'}));let candleCalls=[];const recovered=await candles(async url=>{candleCalls.push(url);return candleCalls.length===1?new Response('',{status:429}):Response.json({candles:rows})},()=>candleNow);assert.equal(recovered.ok,true);assert.equal(recovered.source,'coinbase-public');assert.equal(recovered.candles,60);assert.equal(recovered.momentum.m1,1);assert(candleCalls[1].includes('/market/products/BTC-USD/candles?'));assert(candleCalls[1].includes('granularity=ONE_MINUTE'));assert.equal(recovered.fallbackReason,'Coinbase candles 429');
const failedCandles=await candles(async()=>new Response('',{status:429}),()=>candleNow);assert.equal(failedCandles.ok,false);assert.equal(failedCandles.status,429);
let readCount=0;const staleCandles=await candles(async()=>++readCount===1?new Response('',{status:429}):Response.json({candles:rows.map(x=>({...x,start:String(Number(x.start)-300)}))}),()=>candleNow);assert.equal(staleCandles.ok,false);assert(staleCandles.error.includes('stale'));console.log('PASS: Coinbase fallback parses minute candles, retains original error, rejects stale data and dual feed failure');

const elements=new Map(),fakeDocument={getElementById:id=>{if(!elements.has(id))elements.set(id,{textContent:'',value:'',setAttribute(){}});return elements.get(id)}};const panelContext=vm.createContext({document:fakeDocument,navigator:{clipboard:{writeText:async()=>{}}},console});vm.runInContext(script,panelContext);const pausedExample={build:'test',enabled:false,paused:'Unresolved order CID',position:{entryOrder:'CID'},orders:[{clientOrderId:'CID',state:'UNCERTAIN',error:'Kalshi POST HTTP 400 (invalid_order)',errorStage:'Kalshi response'}],lastError:{method:'POST',path:'/portfolio/events/orders'}};panelContext.example=pausedExample;vm.runInContext('showStatus(example)',panelContext);assert(elements.get('diagnosis').textContent.includes('Original submission error: Kalshi POST HTTP 400'));assert(elements.get('diagnosis').textContent.includes('POST /portfolio/events/orders'));const details=vm.runInContext('troubleshooting(example)',panelContext);assert.equal(details.submissionStage,'Kalshi response');assert(!('token' in details));console.log('PASS: owner page prominently shows original submission error and exports diagnostics without the token');

const krakenRows=rows.map(x=>[Number(x.start),x.open,x.high,x.low,x.close,x.close,x.volume,1]);
let providerCalls=[];const independent=await candles(async url=>{providerCalls.push(url);return url.includes('api.kraken.com')?Response.json({error:[],result:{XXBTZUSD:krakenRows,last:123}}):new Response('',{status:429})},()=>candleNow);
assert.equal(independent.ok,true);assert.equal(independent.source,'kraken-public');assert.equal(independent.candles,60);assert.equal(independent.momentum.m1,1);assert.equal(providerCalls.length,3);assert(independent.fallbackReason.includes('Coinbase public candles 429'));assert.equal(independent.providerRetryAt['coinbase-exchange'],candleNow+300000);
providerCalls=[];const cooldownRecovery=await candles(async url=>{providerCalls.push(url);return Response.json({error:[],result:{XXBTZUSD:krakenRows}})},()=>candleNow+31000,independent.providerRetryAt);assert.equal(cooldownRecovery.ok,true);assert.equal(providerCalls.length,1);assert(providerCalls[0].includes('api.kraken.com'));
for(const bad of [{error:['EAPI:Rate limit exceeded'],result:{}},{error:[],result:{XXBTZUSD:krakenRows.map(x=>[x[0]-300,...x.slice(1)])}},{error:[],result:{XXBTZUSD:krakenRows.map(x=>[x[0],x[1],x[2],x[3],'bad',...x.slice(5)])}}]){const d=await candles(async url=>url.includes('api.kraken.com')?Response.json(bad):new Response('',{status:429}),()=>candleNow);assert.equal(d.ok,false)}
const providerMap=new Map;const providerStorage={get:async k=>structuredClone(providerMap.get(k)),put:async(k,v)=>providerMap.set(k,structuredClone(v))};const {CandleFeed:SharedFeed}=await import('./candle-feed.mjs');let feedTime=candleNow;const firstFeed=new SharedFeed(providerStorage,async()=>independent,()=>feedTime);await firstFeed.get();feedTime+=31000;const restartedFeed=new SharedFeed(providerStorage,async options=>{assert.equal(options.providerRetryAt['coinbase-exchange'],candleNow+300000);return cooldownRecovery},()=>feedTime);assert.equal((await restartedFeed.get()).source,'kraken-public');
console.log('PASS: independent Kraken fallback, per-provider cooldown across restart, API error/malformed/stale candle rejection');

assert.equal(providerCalls[0],'https://api.kraken.com/0/public/OHLC?pair=XBTUSD&interval=1');
const krakenLimited=await candles(async url=>url.includes('api.kraken.com')?Response.json({error:['EAPI:Rate limit exceeded']}):new Response('',{status:429}),()=>candleNow);assert(krakenLimited.error.includes('EAPI:Rate limit exceeded'));assert.equal(krakenLimited.providerRetryAt['kraken-public'],candleNow+300000);
console.log('PASS: simple Kraken request, original public API error and rate-limit cooldown');

const origin='https://huntergunther52.github.io';const activityReq=new Request('https://worker/api/auto/activity',{headers:{origin,authorization:'Bearer '+env.AUTO_TRADING_OWNER_TOKEN}});const beforeActivity=structuredClone([...map]);let brokerRead=false;p.autoEngine.broker.balance=async()=>{brokerRead=true;throw Error('must not read exchange')};const activityResponse=await worker.fetch(activityReq,env,{});assert.equal(activityResponse.headers.get('access-control-allow-origin'),origin);const activity=await activityResponse.json();assert.equal(activity.enabled,false);assert.equal(brokerRead,false);assert.deepEqual([...map],beforeActivity);assert(!JSON.stringify(activity).includes(env.AUTO_TRADING_OWNER_TOKEN));const deniedActivity=await worker.fetch(new Request('https://worker/api/auto/activity',{headers:{origin}}),env,{});assert.equal(deniedActivity.status,401);assert.equal(deniedActivity.headers.get('access-control-allow-origin'),origin);const preflight=await worker.fetch(new Request('https://worker/api/auto/activity',{method:'OPTIONS',headers:{origin}}),env,{});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('access-control-allow-headers'),'Authorization');assert.equal((await worker.fetch(new Request('https://worker/api/auto/activity',{method:'POST'}),env,{})).status,405);
const act=activitySnapshot({enabled:true,position:{ticker:'T',side:'YES',entryOrder:'c',exitOrders:[],requested:6,remaining:2},orders:[{clientOrderId:'c',orderId:'exchange-id',state:'RECONCILED',filledQuantity:2}],history:[]},'live');assert.equal(act.trade.entryFilled,2);assert.equal(act.entryOrder.orderId,'exchange-id');assert.equal(act.active,true);
console.log('PASS: private read-only activity, owner auth, exact-origin CORS, no broker calls/state writes, confirmed fills');

// Attention checks must use existing state, never broker orders, and public push content excludes private details.
map.set('autoTrading:v1',{enabled:false,runRequested:true,paused:'Account mismatch SECRET_ORDER_ID',position:null,history:[],orders:[],recovery:{startedAt:Date.now(),eligible:false}});
map.delete('autoAttention:v1');let attentionSends=0;p.pushAll=async entry=>{attentionSends++;assert.equal(entry.kind,'BOT_ATTENTION');return{sent:1,subscriptions:1}};await p.notifyAutoHealth();await p.notifyAutoHealth();assert.equal(attentionSends,1);const attention=await(await p.fetch(new Request('https://collector/latest-alert'))).json();assert.equal(attention.alert.kind,'BOT_ATTENTION');assert(!JSON.stringify(attention).includes('SECRET_ORDER_ID'));assert(map.get('autoAttention:v1').sentAt);console.log('PASS: Worker attention notification integration, durable deduplication and public privacy');

const {confirmScalp,quoteHistory,rsi}=await import('./worker-v450.js');
const quoteNow=1800000000000;
const rising=(side='YES')=>[0,10000,20000].map((dt,i)=>({ticker:'Q',at:quoteNow-20000+dt,yes_bid:side==='YES'?.49+i*.01:.49-i*.01,yes_ask:side==='YES'?.50+i*.01:.50-i*.01,no_bid:side==='NO'?.49+i*.01:.49-i*.01,no_ask:side==='NO'?.50+i*.01:.50-i*.01}));
const candidate=(side='YES')=>({side,direction:side,entry:.52,confidence:.92,blockers:[],status:'TRADE '+side});
const feature=r=>({experimental:{rsi14:r}});
for(const [side,value] of [['YES',60],['NO',40]]){const h=rising(side),m=h.at(-1),sc=confirmScalp(candidate(side),m,feature(value),h,quoteNow);assert.equal(sc.side,side);assert.equal(sc.confirmation.passed,true)}
for(const [side,value] of [['YES',70],['YES',80],['YES',40],['NO',30],['NO',20],['NO',60],['YES',null]]){const h=rising(side),sc=confirmScalp(candidate(side),h.at(-1),feature(value),h,quoteNow);assert.equal(sc.side,null);assert(sc.reason.includes('RSI'))}
const risingYes=rising(),finalQuote=risingYes.at(-1);
for(const h of [risingYes.map(r=>({...r,ticker:'OLD'})),risingYes.slice(-1),risingYes.map(r=>({...r,at:r.at-120000}))])assert.equal(confirmScalp(candidate(),finalQuote,feature(60),h,quoteNow).side,null);
const falling=rising('NO');assert.equal(confirmScalp(candidate(),falling.at(-1),feature(60),falling,quoteNow).side,null);
const askOnly=risingYes.map(r=>({...r,yes_bid:.49}));assert.equal(confirmScalp(candidate(),askOnly.at(-1),feature(60),askOnly,quoteNow).side,null);
const wide=risingYes.map(r=>({...r,yes_ask:r.yes_bid+.06}));assert(confirmScalp(candidate(),wide.at(-1),feature(60),wide,quoteNow).reason.includes('spread'));
assert.equal(quoteHistory(risingYes,{...finalQuote,ticker:'NEW'},quoteNow).length,1);
assert.equal(quoteHistory(risingYes,finalQuote,quoteNow+1000).length,3);
assert.equal(quoteHistory(risingYes,finalQuote,quoteNow+16000).length,1);
assert.equal(confirmScalp({...candidate(),side:null,blockers:['existing blocker']},finalQuote,feature(60),risingYes,quoteNow).side,null);
assert.equal(rsi(Array(20).fill(1)),50);assert.equal(rsi(Array.from({length:20},(_,i)=>i)),100);assert.equal(rsi(Array.from({length:20},(_,i)=>20-i)),0);assert.equal(rsi([1,2]),null);
// Both the alarm path and app path use the same persisted, serialized confirmation history.
const savedNow=Date.now;Date.now=()=>quoteNow;
try{map.set('kalshiQuoteHistory:v1',risingYes);const gated=await p.confirmScalp(finalQuote,candidate(),feature(80));assert.equal(gated.side,null);assert.equal(gated.confirmation.rsi14,80)}finally{Date.now=savedNow}
console.log('PASS: YES/NO Kalshi trend + RSI gates, extremes/conflicts, stale/wrong-market/ask-only/wide quotes, warm-up, polling deduplication, Wilder RSI and shared DO confirmation');
