import v44,{PriceHistory as V44PriceHistory} from './worker-v425.js';
export class PriceHistory extends V44PriceHistory{
 async scalpPaper(m,sc){let log=(await this.state.storage.get('scalpLog'))||[],o=(await this.state.storage.get('scalpOpen'))||null,now=Date.now();
  if(o){const bid=o.side==='YES'?Number(m.yes_bid):Number(m.no_bid),age=(now-o.openedAt)/1000;let why=null,exit=null;if(Number.isFinite(bid)&&bid>=o.takeProfit){why='TAKE PROFIT';exit=bid}else if(Number.isFinite(bid)&&bid<=o.stop){why='STOP';exit=bid}else if(age>=o.maxHoldSeconds||o.ticker!==m.ticker){why='TIMEOUT';exit=Number.isFinite(bid)?bid:o.entry}
   if(why){o={...o,status:'CLOSED',exit,closedAt:now,exitReason:why,pnlPct:o.entry>0?(exit-o.entry)/o.entry:null,won:exit>o.entry};log.push(o);await this.state.storage.put('scalpLog',log.slice(-500));await this.state.storage.delete('scalpOpen');o=null}}
  if(!o&&sc?.side){const seen=(await this.state.storage.get('scalpPaperSeen'))||[],key=m.ticker+':'+sc.side;if(!seen.includes(key)){o={ticker:m.ticker,side:sc.side,entry:sc.entry,takeProfit:sc.targetPrice,stop:sc.stopPrice,confidence:sc.confidence,openedAt:now,maxHoldSeconds:90,status:'OPEN'};await this.state.storage.put('scalpOpen',o);seen.push(key);await this.state.storage.put('scalpPaperSeen',seen.slice(-500))}}
  return{open:o,log}
 }
 async pushAll(entry){const subs=(await this.state.storage.get('subs'))||[];if(!subs.length)return{sent:0,subscriptions:0};const k=await ensureVapidLocal(this.state),keep=[];let sent=0;for(const sub of subs){const st=await sendPushLocal(sub,k);if(st>=200&&st<300)sent++;if(st!==404&&st!==410)keep.push(sub)}await this.state.storage.put('subs',keep);await this.state.storage.put('pushHealth',{at:Date.now(),sent,subscriptions:subs.length,last:entry});return{sent,subscriptions:subs.length}}
 async checkSignal(){await this.load();const x=await this.getMarket();if(x.status!=='live'||!x.market)return;const m=x.market,base={market:m,btc:{latest:this.points.at(-1)},timing:{seconds_remaining:Math.max(0,(Date.parse(m.close_time||m.expiration_time)-Date.now())/1000)}};const ft=await candles(),b=modelB(base,ft),sc=scalpModel(base,ft);await this.state.storage.put('latestModelB',b);await this.state.storage.put('latestScalp',sc);await this.scalpPaper(m,sc);const signals=[];if(b?.best)signals.push({kind:'SETTLEMENT',side:b.best.side,price:b.best.market,confidence:b.best.probability,edge:b.best.edge,mult:b.best.mult});if(sc?.side)signals.push({kind:'SCALP',side:sc.side,price:sc.entry,confidence:sc.confidence,targetPrice:sc.targetPrice,stopPrice:sc.stopPrice,hold:sc.expectedHoldSeconds});const seen=(await this.state.storage.get('allTradeAlertSeen'))||[];for(const z of signals){const key=m.ticker+':'+z.kind+':'+z.side;if(seen.includes(key))continue;const entry={...z,ticker:m.ticker,btc:base.btc.latest?.p,target:m.target,timeLeft:Math.round(base.timing.seconds_remaining),at:Date.now()};await this.pushAll(entry);seen.push(key);await this.state.storage.put('lastPush',entry)}await this.state.storage.put('allTradeAlertSeen',seen.slice(-1000))}
 async fetch(req){const u=new URL(req.url);if(u.pathname.endsWith('/scalp-performance')){const log=(await this.state.storage.get('scalpLog'))||[],open=(await this.state.storage.get('scalpOpen'))||null,wins=log.filter(x=>x.won).length,pnl=log.reduce((a,x)=>a+(Number.isFinite(x.pnlPct)?x.pnlPct:0),0);return json({ok:true,version:VERSION,open,trades:log.length,wins,losses:log.length-wins,winRate:log.length?wins/log.length:null,totalReturnPct:pnl*100,history:log.slice(-50).reverse()})}if(u.pathname.endsWith('/push-health'))return json({ok:true,...((await this.state.storage.get('pushHealth'))||{}),subscriptions:((await this.state.storage.get('subs'))||[]).length});return super.fetch(req)}
}
const VERSION='4.8.0',cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Cache-Control':'no-store'};
const json=(o,s=200)=>new Response(JSON.stringify(o,null,2),{status:s,headers:{...cors,'content-type':'application/json'}});
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function b64uL(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}function b64udL(s){s=String(s||'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),x=>x.charCodeAt(0))}function str64L(s){return b64uL(new TextEncoder().encode(s))}
async function ensureVapidLocal(state){let k=await state.storage.get('vapid');if(k?.pub&&k?.priv)return k;const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),priv=await crypto.subtle.exportKey('jwk',pair.privateKey),pub=await crypto.subtle.exportKey('jwk',pair.publicKey),raw=new Uint8Array(65);raw[0]=4;raw.set(b64udL(pub.x),1);raw.set(b64udL(pub.y),33);k={priv,pub:b64uL(raw)};await state.storage.put('vapid',k);return k}
async function sendPushLocal(sub,k){try{const aud=new URL(sub.endpoint).origin,h=str64L(JSON.stringify({typ:'JWT',alg:'ES256'})),b=str64L(JSON.stringify({aud,exp:Math.floor(Date.now()/1000)+3600,sub:'mailto:btc15-alerts@users.noreply.github.com'})),key=await crypto.subtle.importKey('jwk',k.priv,{name:'ECDSA',namedCurve:'P-256'},false,['sign']),sig=new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,new TextEncoder().encode(h+'.'+b))),auth='vapid t='+h+'.'+b+'.'+b64uL(sig)+', k='+k.pub;return(await fetch(sub.endpoint,{method:'POST',headers:{TTL:'60',Urgency:'high',Authorization:auth}})).status}catch{return 0}}

function std(a){if(a.length<2)return 0;const m=a.reduce((s,x)=>s+x,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function ema(a,n){if(!a.length)return null;const k=2/(n+1);let e=a[0];for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<n+1)return null;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}if(!l)return 100;const rs=(g/n)/(l/n);return 100-100/(1+rs)}
async function candles(){try{const end=new Date(),start=new Date(end.getTime()-60*60*1000),u='https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=60&start='+encodeURIComponent(start.toISOString())+'&end='+encodeURIComponent(end.toISOString()),r=await fetch(u,{headers:{accept:'application/json','user-agent':'btc15-signal'}});if(!r.ok)throw Error('Coinbase candles '+r.status);const a=(await r.json()).map(x=>({t:x[0]*1000,low:+x[1],high:+x[2],open:+x[3],close:+x[4],volume:+x[5]})).sort((a,b)=>a.t-b.t);const closes=a.map(x=>x.close),vols=a.map(x=>x.volume),rets=[];for(let i=1;i<closes.length;i++)rets.push((closes[i]-closes[i-1])/closes[i-1]);const fast=ema(closes,12),slow=ema(closes,26),macd=fast!=null&&slow!=null?fast-slow:null;let hist=null;if(closes.length>=35){const series=[];for(let i=26;i<=closes.length;i++){const s=closes.slice(0,i);series.push(ema(s,12)-ema(s,26))}const sig=ema(series,9);if(sig!=null)hist=macd-sig}const lastVol=vols.at(-1)||0,avgVol=vols.slice(-11,-1).reduce((s,x)=>s+x,0)/Math.max(1,vols.slice(-11,-1).length),vr=avgVol?lastVol/avgVol:null,rv=std(rets.slice(-10))*Math.sqrt(10),m1=closes.length>1?closes.at(-1)-closes.at(-2):0,m3=closes.length>3?closes.at(-1)-closes.at(-4):0,m5=closes.length>5?closes.at(-1)-closes.at(-6):0;return{ok:true,candles:a.length,last_close:closes.at(-1),volume:{last:lastVol,avg10:avgVol,ratio:vr,confirmation:vr>=1.15?'STRONG':vr>=.8?'NORMAL':'WEAK'},momentum:{m1,m3,m5},volatility:{realized10:rv,regime:rv>.006?'HIGH':rv>.0025?'NORMAL':'LOW'},experimental:{rsi14:rsi(closes),macd,macdHistogram:hist}}}catch(e){return{ok:false,error:String(e.message||e)}}}
function scalpModel(base,f){if(!base?.market||!base?.btc?.latest||!f?.ok)return null;const m=base.market,p=base.btc.latest.p,rem=+base.timing?.seconds_remaining||300,ya=+m.yes_ask,na=+m.no_ask;if(!Number.isFinite(ya)||!Number.isFinite(na))return null;const mom=f.momentum.m1*.50+f.momentum.m3*.30+f.momentum.m5*.20,vr=Number.isFinite(+f.volume.ratio)?+f.volume.ratio:1,rv=Math.max(.00015,f.volatility.realized10||.001),noise=Math.max(8,p*rv*.10),strength=Math.abs(mom)/noise,dir=mom>=0?'YES':'NO',entry=dir==='YES'?ya:na,confidence=clamp(.50+.18*strength+.10*clamp((vr-.5)/.8,0,1)-(f.volatility.regime==='HIGH'?.05:0),.05,.92),move=clamp(.025+.055*strength+.025*clamp(vr,0,2),.03,.12),targetPrice=clamp(entry+move,.02,.98),stopPrice=clamp(entry-Math.max(.025,move*.6),.01,.97),qualifies=entry>.04&&entry<.96&&rem>=15&&rem<=600&&Math.abs(mom)>=3&&confidence>=.54;return{status:qualifies?'TRADE '+dir:'WATCH '+dir,side:qualifies?dir:null,direction:dir,confidence,entry,targetPrice,stopPrice,expectedHoldSeconds:strength>1.25?'20–45':'30–90',momentumScore:mom,volumeRatio:vr,timeLeft:Math.round(rem),reason:qualifies?'Short-term '+dir+' momentum setup':'Directional lean only — waiting for a tradable move'}}
function modelB(base,f){if(!base?.market||!base?.btc?.latest||!f?.ok)return null;const m=base.market,p=base.btc.latest.p,t=+m.target,rem=+base.timing?.seconds_remaining||300,ym=+m.yes_ask,nm=+m.no_ask;if(!Number.isFinite(t)||!Number.isFinite(ym)||!Number.isFinite(nm))return null;const mom=(f.momentum.m1*.5+f.momentum.m3*.25+f.momentum.m5*.15),volRatio=f.volume.ratio||1,volConfirm=clamp((volRatio-.65)/.9,0,1),rv=Math.max(.00015,f.volatility.realized10||.001),scale=Math.max(18,p*rv*Math.sqrt(Math.max(10,rem)/600)),z=(p-t+mom*(.55+.45*volConfirm))/scale,raw=1/(1+Math.exp(-1.55*z)),regimePenalty=f.volatility.regime==='HIGH'?.68:f.volatility.regime==='LOW'?.82:1,confidence=.5+(raw-.5)*regimePenalty,yp=clamp(.78*confidence+.22*ym,.03,.97),np=1-yp;const yes={side:'YES',probability:yp,market:ym,edge:yp-ym,mult:ym>0?1/ym:null},no={side:'NO',probability:np,market:nm,edge:np-nm,mult:nm>0?1/nm:null};const predicted=yp>=.5?yes:no,value=yes.edge>=no.edge?yes:no;const predEdge=predicted.edge,qualifies=predicted.probability>=.54&&predEdge>=.025&&rem>=20&&rem<=600&&predicted.market>.04&&predicted.market<.96;const best=qualifies?predicted:null;return{yes,no,predicted,value,best,bet:qualifies?predicted.side:'NO BET',inputs:{momentumScore:mom,volumeRatio:volRatio,volumeConfirmation:f.volume.confirmation,volatilityRegime:f.volatility.regime},status:qualifies?'PAPER SIGNAL':'WAIT'}}
async function current(req,env,ctx){const r=await v44.fetch(req,env,ctx),base=await r.clone().json();if(!base?.ok)return r;let f=await candles();let b=modelB(base,f),scalp=scalpModel(base,f);if(f?.ok&&b){try{await env.PRICE_HISTORY.get(env.PRICE_HISTORY.idFromName('global')).fetch('https://do/modelb-cache',{method:'POST',body:JSON.stringify({f,b,at:Date.now(),ticker:base.market?.ticker})})}catch{}}else{try{const cr=await env.PRICE_HISTORY.get(env.PRICE_HISTORY.idFromName('global')).fetch('https://do/modelb-cache');if(cr.ok){const z=await cr.json();if(z?.b&&Date.now()-z.at<120000&&(!z.ticker||z.ticker===base.market?.ticker)){f=z.f;b=z.b;f={...f,cached:true}}}}catch{}}return json({...base,version:VERSION,features:f,scalp,ab_test:{modelA:{name:'Baseline',description:'Existing price/target + short momentum model',status:'BASELINE'},modelB:{name:'Momentum + Volume',description:'Price momentum confirmed by real Coinbase volume; volatility adjusts confidence',...b},experimental_only:['RSI 14','MACD histogram']},architecture:{...(base.architecture||{}),ab_test:true,coinbase_volume:true,volatility_filter:true}})}
export default{async fetch(req,env,ctx){const u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{headers:cors});if(u.pathname==='/'||u.pathname==='/health')return json({ok:true,service:'btc15-api',version:VERSION,ab_test:true,model_b:'momentum + volume',volatility_filter:true,rsi_macd:'recorded only',scalp_mode:true,time:new Date().toISOString()});if(u.pathname==='/api/scalp-performance')return env.PRICE_HISTORY.get(env.PRICE_HISTORY.idFromName('btc-usd')).fetch('https://do/scalp-performance');if(u.pathname==='/api/push-health')return env.PRICE_HISTORY.get(env.PRICE_HISTORY.idFromName('btc-usd')).fetch('https://do/push-health');if(u.pathname==='/api/current')try{return await current(req,env,ctx)}catch(e){return json({ok:false,version:VERSION,error:String(e?.message||e)},502)}return v44.fetch(req,env,ctx)}};