import legacy, { PriceHistory as LegacyPriceHistory } from "./index.js";

const VERSION="4.4.0",KALSHI="https://api.elections.kalshi.com/trade-api/v2",SERIES="KXBTC15M";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Cache-Control":"no-store"};
const json=(o,s=200)=>new Response(JSON.stringify(o,null,2),{status:s,headers:{...cors,"content-type":"application/json"}});
const num=(...xs)=>{for(const x of xs){const n=Number(x);if(Number.isFinite(n))return n}return null},pp=v=>{const n=Number(v);return Number.isFinite(n)?(n>1?n/100:n):null},clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const closeOf=m=>Date.parse(m?.close_time||m?.expiration_time||m?.expected_expiration_time||0);
function target(m){if(!m)return null;const d=num(m.floor_strike,m.strike,m.target,m.custom_strike?.target,m.custom_strike?.value);if(d&&d>1000)return d;for(const s of[m.functional_strike,m.subtitle,m.title,m.yes_sub_title]){const z=String(s||"").match(/\$?\s*([0-9]{2,3}(?:,[0-9]{3})+(?:\.[0-9]+)?)/);if(z)return Number(z[1].replaceAll(",",""))}return null}
async function get(path){const r=await fetch(KALSHI+path,{headers:{accept:"application/json"},cf:{cacheTtl:0}});if(!r.ok){const e=Error(`Kalshi ${r.status}: ${(await r.text()).slice(0,160)}`);e.status=r.status;throw e}return r.json()}
function cdf(x){const t=1/(1+.2316419*Math.abs(x)),d=.3989423*Math.exp(-x*x/2);let p=1-d*t*(.319381530+t*(-.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));return x>=0?p:1-p}function std(v){if(v.length<2)return 0;const a=v.reduce((s,x)=>s+x,0)/v.length;return Math.sqrt(v.reduce((s,x)=>s+(x-a)**2,0)/(v.length-1))}
function b64u(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}function b64ud(s){s=String(s||"").replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}function str64(s){return b64u(new TextEncoder().encode(s))}
async function ensureVapid(state){let k=await state.storage.get("vapid");if(k?.pub&&k?.priv)return k;const pair=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]),priv=await crypto.subtle.exportKey("jwk",pair.privateKey),pub=await crypto.subtle.exportKey("jwk",pair.publicKey),raw=new Uint8Array(65);raw[0]=4;raw.set(b64ud(pub.x),1);raw.set(b64ud(pub.y),33);k={priv,pub:b64u(raw)};await state.storage.put("vapid",k);return k}
async function vapidHeaders(endpoint,k){const aud=new URL(endpoint).origin,h=str64(JSON.stringify({typ:"JWT",alg:"ES256"})),b=str64(JSON.stringify({aud,exp:Math.floor(Date.now()/1000)+3600,sub:"mailto:btc15-alerts@users.noreply.github.com"})),key=await crypto.subtle.importKey("jwk",k.priv,{name:"ECDSA",namedCurve:"P-256"},false,["sign"]),sig=new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,new TextEncoder().encode(h+"."+b)));return{TTL:"60",Urgency:"high",Authorization:`vapid t=${h}.${b}.${b64u(sig)}, k=${k.pub}`}}
async function sendPush(sub,k){try{return(await fetch(sub.endpoint,{method:"POST",headers:await vapidHeaders(sub.endpoint,k)})).status}catch{return 0}}
function bucket(mult){return mult<3?"2-3x":mult<4?"3-4x":mult<5?"4-5x":"5x+"}
function paperSignal(m,pts){if(!m||pts.length<20)return null;const now=Date.now(),rem=(closeOf(m)-now)/1000;if(rem<=8||rem>300)return null;const latest=pts.at(-1),tgt=target(m);if(!Number.isFinite(tgt))return null;const old=ms=>[...pts].reverse().find(x=>x.t<=now-ms)||pts[0],m15=latest.p-old(15000).p,m30=latest.p-old(30000).p,recent=pts.filter(x=>now-x.t<=30000),chg=[];for(let i=1;i<recent.length;i++)chg.push(recent[i].p-recent[i-1].p);const vol=std(chg),dist=latest.p-tgt,sec=Math.max(10,Math.min(rem,300)),sigma=Math.max(18,vol*4.5*Math.sqrt(sec/15)),trend=.18*m15+.08*m30,raw=cdf((dist+trend)/sigma),strength=clamp(.22+(300-rem)/300*.78,.22,1),ym=pp(m.yes_ask_dollars??m.yes_ask),nm=pp(m.no_ask_dollars??m.no_ask);if(!Number.isFinite(ym)||!Number.isFinite(nm))return null;let yp=.5+(raw-.5)*strength;yp=clamp(.85*yp+.15*ym,.03,.97);const sides=[{side:"YES",price:ym,model:yp},{side:"NO",price:nm,model:1-yp}].map(x=>({...x,mult:x.price>0?1/x.price:0,edge:x.model-x.price})).filter(x=>x.mult>=2&&x.edge>=.10&&x.model>=.40);if(!sides.length)return null;const x=sides.sort((a,b)=>b.edge-a.edge)[0];return{side:x.side,marketPct:x.price*100,modelPct:x.model*100,edge:x.edge*100,mult:x.mult,band:bucket(x.mult),timeLeft:Math.round(rem),ticker:m.ticker,btc:latest.p,target:tgt,at:now}}
function stats(log){const bands=["2-3x","3-4x","4-5x","5x+"];const out={};for(const band of bands){const all=log.filter(x=>x.band===band),s=all.filter(x=>x.result),wins=s.filter(x=>x.won).length,pnl=s.reduce((a,x)=>a+(x.won?(x.mult-1):-1),0),roi=s.length?pnl/s.length:null,avgMult=s.length?s.reduce((a,x)=>a+x.mult,0)/s.length:null,breakEven=avgMult?1/avgMult:null;out[band]={paperSignals:all.length,settled:s.length,wins,losses:s.length-wins,winRate:s.length?wins/s.length:null,avgMultiplier:avgMult,breakEvenRate:breakEven,hypotheticalUnitsPnl:pnl,roi,actionable:s.length>=20&&roi>.05&&wins/s.length>(breakEven||1),status:s.length<20?"PAPER TESTING":(roi>.05&&wins/s.length>(breakEven||1)?"ALERT ENABLED":"PAPER ONLY")}}return out}
export class PriceHistory extends LegacyPriceHistory{
 async settlePaper(activeTicker){let log=(await this.state.storage.get("paperLog"))||[],changed=false;for(const x of log){if(x.result||x.ticker===activeTicker)continue;try{const d=await get(`/markets/${encodeURIComponent(x.ticker)}`),m=d.market;if(m&&(m.result||m.status==="settled")){const r=String(m.result||"").toUpperCase();if(r==="YES"||r==="NO"){x.result=r;x.won=r===x.side;x.settledAt=Date.now();changed=true}}}catch{}}if(changed)await this.state.storage.put("paperLog",log.slice(-1000));return log}
 async checkSignal(){const x=await this.getMarket();if(x.status!=="live"||!x.market){await this.state.storage.delete("paperCandidate");return}let log=await this.settlePaper(x.market.ticker),s=paperSignal(x.market,this.points);await this.state.storage.put("latestSignal",s);if(!s){await this.state.storage.delete("paperCandidate");return}let c=(await this.state.storage.get("paperCandidate"))||null;if(c&&c.ticker===s.ticker&&c.side===s.side&&c.band===s.band)c={...s,count:(c.count||1)+1,firstAt:c.firstAt||s.at};else c={...s,count:1,firstAt:s.at};await this.state.storage.put("paperCandidate",c);if(c.count<3)return;const key=`${s.ticker}:${s.side}:${s.band}`,seen=(await this.state.storage.get("paperSeen"))||[];if(seen.includes(key))return;const perf=stats(log),gate=perf[s.band],entry={...s,confirmedReadings:c.count,loggedAt:Date.now(),result:null,won:null,mode:gate?.actionable?"ACTIONABLE":"PAPER",gateStatus:gate?.status||"PAPER TESTING"};log.push(entry);await this.state.storage.put("paperLog",log.slice(-1000));seen.push(key);await this.state.storage.put("paperSeen",seen.slice(-500));if(!gate?.actionable)return;const subs=(await this.state.storage.get("subs"))||[];if(!subs.length)return;const k=await ensureVapid(this.state),keep=[];for(const sub of subs){const st=await sendPush(sub,k);if(st!==404&&st!==410)keep.push(sub)}await this.state.storage.put("subs",keep);await this.state.storage.put("lastPush",{...s,at:Date.now(),performanceGated:true})}
 async fetch(req){const u=new URL(req.url);if(u.pathname.endsWith("/performance")){await this.load();let log=await this.settlePaper(null);const bands=stats(log),settled=log.filter(x=>x.result),wins=settled.filter(x=>x.won).length;return json({ok:true,version:VERSION,mode:"performance-gated",minimumSettledPerBand:20,minimumRoiForAlerts:.05,totalPaperSignals:log.length,settled:settled.length,wins,losses:settled.length-wins,winRate:settled.length?wins/settled.length:null,bands,alerts:log.slice(-100).reverse()})}return super.fetch(req)}
}
function choose(markets){const now=Date.now();return(markets||[]).filter(m=>m&&m.ticker&&closeOf(m)>now+5000).sort((a,b)=>closeOf(a)-closeOf(b))[0]||null}
async function discover(){const attempts=[];for(const[route,path,nested]of[["markets-open",`/markets?series_ticker=${SERIES}&status=open&limit=100`,false],["markets-all",`/markets?series_ticker=${SERIES}&limit=100`,false],["events-open",`/events?series_ticker=${SERIES}&status=open&with_nested_markets=true&limit=100`,true],["events-all",`/events?series_ticker=${SERIES}&with_nested_markets=true&limit=100`,true]]){try{const d=await get(path),a=nested?(d.events||[]).flatMap(e=>e.markets||[]):(d.markets||[]),m=choose(a);attempts.push({route,count:a.length});if(m)return{market:m,route,attempts}}catch(e){attempts.push({route,error:String(e.message||e)})}}return{market:null,route:null,attempts}}
async function freshMarket(m){if(!m?.ticker)return m;try{return(await get(`/markets/${encodeURIComponent(m.ticker)}`)).market||m}catch{return m}}
function prices(m){let ya=pp(m.yes_ask_dollars??m.yes_ask),na=pp(m.no_ask_dollars??m.no_ask),yb=pp(m.yes_bid_dollars??m.yes_bid),nb=pp(m.no_bid_dollars??m.no_bid);if(!Number.isFinite(ya)&&Number.isFinite(nb))ya=1-nb;if(!Number.isFinite(na)&&Number.isFinite(yb))na=1-yb;return{yes_bid:yb,yes_ask:ya,no_bid:nb,no_ask:na}}
function normalized(m){return{ticker:m.ticker,event_ticker:m.event_ticker,title:m.title,subtitle:m.subtitle,close_time:m.close_time||m.expiration_time||m.expected_expiration_time,target:target(m),...prices(m)}}
async function fixedCurrent(req,env){const oldResp=await legacy.fetch(req,env);let base;try{base=await oldResp.clone().json()}catch{return oldResp}let raw=null,route="legacy-cache",attempts=[];if(base?.ok&&base?.market?.ticker){try{raw=(await get(`/markets/${encodeURIComponent(base.market.ticker)}`)).market||null;route="ticker-refresh"}catch{}}if(!raw){const d=await discover();raw=d.market;route=d.route||"fallback-none";attempts=d.attempts}if(!raw)return json({...base,ok:true,version:VERSION,market_status:"waiting",status:"waiting",message:"Waiting for next BTC 15-minute market.",market_discovery:route,discovery_attempts:attempts});raw=await freshMarket(raw);const m=normalized(raw),ms=Math.max(0,Date.parse(m.close_time)-Date.now());return json({...base,ok:true,version:VERSION,server_time:new Date().toISOString(),market_status:"live",status:"live",message:undefined,market:m,timing:{ms_remaining:ms,seconds_remaining:ms/1000,final_60:ms>0&&ms<=60000},market_discovery:route,discovery_attempts:attempts,architecture:{...(base.architecture||{}),performance_gated:true,paper_bands:true}})}
export default{async fetch(req,env,ctx){const u=new URL(req.url);if(req.method==="OPTIONS")return new Response(null,{headers:cors});if(u.pathname==="/"||u.pathname==="/health")return json({ok:true,service:"btc15-api",version:VERSION,background_push:true,performance_gated:true,paper_bands:["2-3x","3-4x","4-5x","5x+"],minimum_settled_per_band:20,time:new Date().toISOString()});if(u.pathname==="/api/current")try{return await fixedCurrent(req,env)}catch(e){return json({ok:false,version:VERSION,error:String(e?.message||e),time:new Date().toISOString()},502)}return legacy.fetch(req,env,ctx)}};