import {CandleFeed} from './candle-feed.mjs';
import v44,{PriceHistory as V44PriceHistory} from './worker-v425.js';
export class PriceHistory extends V44PriceHistory{
 async scalpPaper(m,sc){
  const prior=this.paperQueue||Promise.resolve();
  const run=prior.catch(()=>{}).then(async()=>{const result=await this.updateScalpPaper(m,sc);if(!await this.state.storage.get('trialStartedAt'))await this.state.storage.put('trialStartedAt',Date.now());for(const trial of TRIALS){try{await this.updateScalpPaper(m,trialEligible(trial,m,sc)?sc:null,'trial:'+trial.id+':')}catch(e){await this.state.storage.put('trialError:'+trial.id,{at:Date.now(),message:String(e.message||e)})}}return result});
  this.paperQueue=run;return run;
 }
 async updateScalpPaper(m,sc,prefix=''){let log=(await this.state.storage.get(prefix+'scalpLog'))||[],o=(await this.state.storage.get(prefix+'scalpOpen'))||null,now=Date.now();
  if(o){let quote=m;if(o.ticker!==m.ticker){const r=await fetch('https://api.elections.kalshi.com/trade-api/v2/markets/'+encodeURIComponent(o.ticker),{headers:{accept:'application/json'}});if(!r.ok)throw Error('Could not read open paper trade market: '+r.status);const old=(await r.json()).market;quote=normalizeMarket(old)}const bid=o.side==='YES'?quote.yes_bid:quote.no_bid,age=(now-o.openedAt)/1000;let why=null,exit=null;if(bid!==null&&Number.isFinite(bid)&&bid>=o.takeProfit){why='TAKE PROFIT';exit=bid}else if(bid!==null&&Number.isFinite(bid)&&bid<=o.stop){why='STOP';exit=bid}else if(age>=o.maxHoldSeconds||o.ticker!==m.ticker){why='TIMEOUT';exit=bid!==null&&Number.isFinite(bid)?bid:o.entry}
   if(why){o={...o,status:'CLOSED',exit,closedAt:now,exitReason:why,pnlPct:o.entry>0?(exit-o.entry)/o.entry:null,won:exit>o.entry};o=accountedTrade(o);log.push(o);await this.state.storage.put(prefix+'scalpLog',log);await this.state.storage.delete(prefix+'scalpOpen');o=null}}
  if(!o&&sc?.side&&Number.isFinite(sc.entry)&&sc.entry>0&&paperSize(sc.entry)>0){const seen=(await this.state.storage.get(prefix+'scalpPaperSeen'))||[],key=m.ticker+':'+sc.side;if(!seen.includes(key)){o={ticker:m.ticker,side:sc.side,entry:sc.entry,takeProfit:sc.targetPrice,stop:sc.stopPrice,confidence:sc.confidence,contracts:paperSize(sc.entry),entryFee:estimatedFee(sc.entry,paperSize(sc.entry),'buy'),openedAt:now,maxHoldSeconds:90,status:'OPEN',...(prefix?{entryInputs:{score:sc.confidence,timeLeft:sc.timeLeft,momentumScore:sc.momentumScore,volumeRatio:sc.volumeRatio,yesBid:m.yes_bid,yesAsk:m.yes_ask,noBid:m.no_bid,noAsk:m.no_ask}}:{})};await this.state.storage.put(prefix+'scalpOpen',o);seen.push(key);await this.state.storage.put(prefix+'scalpPaperSeen',seen.slice(-500))}}
  return{open:o,log}
 }
 async pushAll(entry){const subs=(await this.state.storage.get('subs'))||[];await this.state.storage.put('latestAlert',entry);if(!subs.length)return{sent:0,subscriptions:0};const k=await ensureVapidLocal(this.state),keep=[],statuses=[];let sent=0;for(const sub of subs){const st=await sendPushLocal(sub,k);statuses.push(st);if(st>=200&&st<300)sent++;if(st!==404&&st!==410)keep.push(sub)}await this.state.storage.put('subs',keep);await this.state.storage.put('pushHealth',{at:Date.now(),sent,subscriptions:subs.length,statuses,last:entry});return{sent,subscriptions:subs.length}}
 async alertSignals(m,sc,b,base={}){const prior=this.alertQueue||Promise.resolve();const run=prior.catch(()=>{}).then(async()=>{const signals=[];if(b?.best)signals.push({kind:'SETTLEMENT',side:b.best.side,price:b.best.market,confidence:b.best.probability,edge:b.best.edge,mult:b.best.mult});if(sc?.side)signals.push({kind:'SCALP',side:sc.side,price:sc.entry,confidence:sc.confidence,targetPrice:sc.targetPrice,stopPrice:sc.stopPrice,hold:sc.expectedHoldSeconds});const seen=(await this.state.storage.get('allTradeAlertSeen'))||[];for(const z of signals){const key=m.ticker+':'+z.kind+':'+z.side;if(seen.includes(key))continue;const attempt=(await this.state.storage.get('alertRetry:'+key))||0;if(Date.now()-attempt<30000)continue;const entry={...z,ticker:m.ticker,btc:base.btc?.latest?.p,target:m.target,timeLeft:Math.round(base.timing?.seconds_remaining||0),at:Date.now()};await this.state.storage.put('alertRetry:'+key,Date.now());const result=await this.pushAll(entry);if(result.sent>0){seen.push(key);await this.state.storage.put('lastPush',entry);await this.state.storage.delete('alertRetry:'+key)}}await this.state.storage.put('allTradeAlertSeen',seen.slice(-1000))});this.alertQueue=run;return run}
 async alarm(){try{await super.alarm();const last=(await this.state.storage.get('scalpEngineHealth'))?.at||0;if(Date.now()-last>=10000&&this.env)await current(new Request('https://worker/api/current'),this.env,{})}catch(e){await this.state.storage.put('alertEngineError',{at:Date.now(),message:String(e.message||e)})}finally{await this.state.storage.setAlarm(Date.now()+1000)}}
 constructor(state,env){super(state,env);this.env=env;this.candleFeed=new CandleFeed(state.storage,options=>candles(undefined,Date.now,options.providerRetryAt))}
 async checkSignal(){await this.load();await this.state.storage.put('signalEngineHealth',{at:Date.now(),points:this.points?.length||0});const x=await this.getMarket();if(x.status!=='live'||!x.market)return;const m=normalizeMarket(x.market),ft=await this.candleFeed.get(),latest=this.points.at(-1)||(ft.ok?{p:ft.last_close}:null),base={market:m,btc:{latest},timing:{seconds_remaining:Math.max(0,(Date.parse(m.close_time||m.expiration_time)-Date.now())/1000)}};const b=modelB(base,ft),sc=scalpModel(base,ft);await this.state.storage.put('latestModelB',b);await this.state.storage.put('latestScalp',sc);await this.state.storage.put('signalDataHealth',signalDataHealth(m,sc,base,ft));await this.scalpPaper(m,sc);await this.alertSignals(m,sc,b,base)}
 async fetch(req){const u=new URL(req.url);if(u.pathname==='/candle-features')return json(await this.candleFeed.get());if(u.pathname==='/scalp-tick'&&req.method==='POST'){const {market,scalp,modelB,base,features}=await req.json();await this.state.storage.put('signalDataHealth',signalDataHealth(market,scalp,base,features));const alarm=await this.state.storage.getAlarm();if(!alarm||alarm<=Date.now())await this.state.storage.setAlarm(Date.now()+1000);const result=await this.scalpPaper(market,scalp);await this.alertSignals(market,scalp,modelB,base);await this.state.storage.put('scalpEngineHealth',{at:Date.now(),ticker:market.ticker});return json({ok:true,open:result.open})}if(u.pathname==='/scalp-experiments'){const rows=[];for(const trial of TRIALS){const log=((await this.state.storage.get('trial:'+trial.id+':scalpLog'))||[]).map(accountedTrade);rows.push({...trial,...trialStats(log),open:(await this.state.storage.get('trial:'+trial.id+':scalpOpen'))||null})}return json({ok:true,version:VERSION,startedAt:(await this.state.storage.get('trialStartedAt'))||null,assumptions:'$5 per trade, ask entry and bid exit, estimated taker fees; no depth or slippage simulation',rows})}if(u.pathname==='/latest-alert')return json({ok:true,alert:(await this.state.storage.get('latestAlert'))||null});if(u.pathname.endsWith('/scalp-performance')){const raw=(await this.state.storage.get('scalpLog'))||[],log=raw.map(accountedTrade),open=(await this.state.storage.get('scalpOpen'))||null,wins=log.filter(x=>x.won===true).length,losses=log.filter(x=>x.netPnlDollars< -1e-9).length,breakeven=log.filter(x=>x.breakeven).length,pnl=log.reduce((a,x)=>a+(x.netPnlDollars||0),0),cost=log.reduce((a,x)=>a+(x.cost||0),0),gross=log.reduce((a,x)=>a+(x.grossPnlDollars||0),0),fees=log.reduce((a,x)=>a+(x.entryFee||0)+(x.exitFee||0),0);let cumulative=0;const history=log.map(x=>({...x,cumulativeNetDollars:(cumulative+=x.netPnlDollars||0)})).reverse();return json({ok:true,version:VERSION,accounting:'estimated-net-taker',feeAssumption:'Taker buy and sell, multiplier 1; direct-member rounding; $5 paper budget; top quotes assumed; actual fills may differ',open,trades:log.length,wins,losses,breakeven,winRate:log.length?wins/log.length:null,totalNetDollars:pnl,totalGrossDollars:gross,totalFeeDollars:fees,totalEntryCostDollars:cost,totalReturnPct:cost?100*pnl/cost:0,history})}if(u.pathname.endsWith('/push-health'))return json({ok:true,...((await this.state.storage.get('pushHealth'))||{}),engine:(await this.state.storage.get('signalEngineHealth'))||null,signalData:(await this.state.storage.get('signalDataHealth'))||null,scalpEngine:(await this.state.storage.get('scalpEngineHealth'))||null,engineError:(await this.state.storage.get('alertEngineError'))||null,subscriptions:((await this.state.storage.get('subs'))||[]).length});return super.fetch(req)}
}
const VERSION='5.0.6',cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Cache-Control':'no-store'};
const json=(o,s=200)=>new Response(JSON.stringify(o,null,2),{status:s,headers:{...cors,'content-type':'application/json'}});
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function b64uL(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}function b64udL(s){s=String(s||'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),x=>x.charCodeAt(0))}function str64L(s){return b64uL(new TextEncoder().encode(s))}
async function ensureVapidLocal(state){let k=await state.storage.get('vapid');if(k?.pub&&k?.priv)return k;const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),priv=await crypto.subtle.exportKey('jwk',pair.privateKey),pub=await crypto.subtle.exportKey('jwk',pair.publicKey),raw=new Uint8Array(65);raw[0]=4;raw.set(b64udL(pub.x),1);raw.set(b64udL(pub.y),33);k={priv,pub:b64uL(raw)};await state.storage.put('vapid',k);return k}
async function sendPushLocal(sub,k){try{const aud=new URL(sub.endpoint).origin,h=str64L(JSON.stringify({typ:'JWT',alg:'ES256'})),b=str64L(JSON.stringify({aud,exp:Math.floor(Date.now()/1000)+3600,sub:'mailto:btc15-alerts@users.noreply.github.com'})),key=await crypto.subtle.importKey('jwk',k.priv,{name:'ECDSA',namedCurve:'P-256'},false,['sign']),sig=new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,new TextEncoder().encode(h+'.'+b))),auth='vapid t='+h+'.'+b+'.'+b64uL(sig)+', k='+k.pub;return(await fetch(sub.endpoint,{method:'POST',headers:{TTL:'60',Urgency:'high',Authorization:auth},signal:AbortSignal.timeout(5000)})).status}catch{return 0}}

function pemDer(pem){const s=String(pem||'').replace(/-----BEGIN [^-]+-----/g,'').replace(/-----END [^-]+-----/g,'').replace(/\s/g,'');return Uint8Array.from(atob(s),x=>x.charCodeAt(0))}
async function kalshiRead(env,path){if(!env.KALSHI_API_KEY_ID||!env.KALSHI_PRIVATE_KEY)throw Error('Kalshi API secrets are missing');const ts=String(Date.now()),signPath='/trade-api/v2'+path.split('?')[0],msg=ts+'GET'+signPath,key=await crypto.subtle.importKey('pkcs8',pemDer(env.KALSHI_PRIVATE_KEY),{name:'RSA-PSS',hash:'SHA-256'},false,['sign']),sig=new Uint8Array(await crypto.subtle.sign({name:'RSA-PSS',saltLength:32},key,new TextEncoder().encode(msg))),headers={'KALSHI-ACCESS-KEY':env.KALSHI_API_KEY_ID,'KALSHI-ACCESS-TIMESTAMP':ts,'KALSHI-ACCESS-SIGNATURE':btoa(String.fromCharCode(...sig)),accept:'application/json'},r=await fetch('https://api.elections.kalshi.com/trade-api/v2'+path,{headers}),t=await r.text();let data;try{data=JSON.parse(t)}catch{data={message:t.slice(0,200)}}return{ok:r.ok,status:r.status,data}}
async function authStatus(env){try{const r=await kalshiRead(env,'/portfolio/balance');return json({ok:true,version:VERSION,authenticated:r.ok,httpStatus:r.status,liveTrading:false,maxRiskDollars:5,balanceCents:r.ok?r.data?.balance:null,portfolioValueCents:r.ok?r.data?.portfolio_value:null,message:r.ok?'Kalshi authentication verified. Live order submission is still disabled.':('Kalshi rejected authentication (HTTP '+r.status+').'),detail:r.ok?null:{code:r.data?.error?.code||r.data?.code||null,message:r.data?.error?.message||r.data?.message||null,details:r.data?.error?.details||r.data?.details||null}})}catch(e){return json({ok:true,version:VERSION,authenticated:false,liveTrading:false,maxRiskDollars:5,message:'Authentication check failed.',detail:String(e.message||e)})}}
function std(a){if(a.length<2)return 0;const m=a.reduce((s,x)=>s+x,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function ema(a,n){if(!a.length)return null;const k=2/(n+1);let e=a[0];for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<n+1)return null;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}if(!l)return 100;const rs=(g/n)/(l/n);return 100-100/(1+rs)}
function validCandles(rows,now){if(!Array.isArray(rows))throw Error('Candle data unavailable');const a=rows.sort((x,y)=>x.t-y.t).slice(-60);if(a.length<6||a.some(x=>![x.t,x.low,x.high,x.open,x.close,x.volume].every(Number.isFinite)||x.close<=0||x.volume<0)||now-a.at(-1).t>120000||a.at(-1).t>now+60000||a.some((x,i)=>i&&x.t<=a[i-1].t))throw Error('Candle data is incomplete or stale');return a}
export async function candles(fetcher=(...args)=>globalThis.fetch(...args),clock=Date.now,providerRetryAt={}){
 const now=clock(),end=new Date(now),start=new Date(now-60*60*1000),nextRetry={...providerRetryAt},errors=[];
 const providers=[
  {name:'coinbase-exchange',label:'Coinbase candles',url:'https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=60',parse:d=>d.map(x=>({t:x[0]*1000,low:+x[1],high:+x[2],open:+x[3],close:+x[4],volume:+x[5]}))},
  {name:'coinbase-public',label:'Coinbase public candles',url:'https://api.coinbase.com/api/v3/brokerage/market/products/BTC-USD/candles?granularity=ONE_MINUTE&start='+Math.floor(start.getTime()/1000)+'&end='+Math.floor(now/1000)+'&limit=100',parse:d=>d.candles?.map(x=>({t:Number(x.start)*1000,low:Number(x.low),high:Number(x.high),open:Number(x.open),close:Number(x.close),volume:Number(x.volume)}))},
  {name:'kraken-public',label:'Kraken candles',url:'https://api.kraken.com/0/public/OHLC?pair=XBTUSD&interval=1',parse:d=>{if(!Array.isArray(d.error))throw Error('Kraken candle response missing error array');if(d.error.length){const detail=d.error.filter(x=>typeof x==='string').map(x=>x.slice(0,150)).join('; ');const e=Error('Kraken candle API error: '+detail);if(/rate limit|throttl/i.test(detail))e.status=429;throw e}return(d.result?.XXBTZUSD||d.result?.['BTC/USD'])?.map(x=>({t:Number(x[0])*1000,open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[6])}))}}
 ];
 let a,source,fallbackReason=null,status;
 for(const provider of providers){if(nextRetry[provider.name]>now){errors.push(provider.label+' cooling down after failure');continue}try{const r=await fetcher(provider.url,{headers:{accept:'application/json'},signal:AbortSignal.timeout(5000)});if(!r.ok){const e=Error(provider.label+' '+r.status);e.status=r.status;throw e}a=validCandles(provider.parse(await r.json()),clock());source=provider.name;delete nextRetry[provider.name];fallbackReason=errors.length?errors.join('; '):null;break}catch(e){status=e.status||status;errors.push(String(e.message||e));nextRetry[provider.name]=clock()+(e.status===429?300000:30000)}}
 if(!a)return{ok:false,status,error:errors.join('; ')||'Candle data unavailable',providerRetryAt:nextRetry};
 const closes=a.map(x=>x.close),vols=a.map(x=>x.volume),rets=[];for(let i=1;i<closes.length;i++)rets.push((closes[i]-closes[i-1])/closes[i-1]);const fast=ema(closes,12),slow=ema(closes,26),macd=fast!=null&&slow!=null?fast-slow:null;let hist=null;if(closes.length>=35){const series=[];for(let i=26;i<=closes.length;i++){const s=closes.slice(0,i);series.push(ema(s,12)-ema(s,26))}const sig=ema(series,9);if(sig!=null)hist=macd-sig}const lastVol=vols.at(-1)||0,avgVol=vols.slice(-11,-1).reduce((s,x)=>s+x,0)/Math.max(1,vols.slice(-11,-1).length),vr=avgVol?lastVol/avgVol:null,rv=std(rets.slice(-10))*Math.sqrt(10),m1=closes.length>1?closes.at(-1)-closes.at(-2):0,m3=closes.length>3?closes.at(-1)-closes.at(-4):0,m5=closes.length>5?closes.at(-1)-closes.at(-6):0;return{ok:true,source,fallbackReason,providerRetryAt:nextRetry,candles:a.length,last_close:closes.at(-1),volume:{last:lastVol,avg10:avgVol,ratio:vr,confirmation:vr>=1.15?'STRONG':vr>=.8?'NORMAL':'WEAK'},momentum:{m1,m3,m5},volatility:{realized10:rv,regime:rv>.006?'HIGH':rv>.0025?'NORMAL':'LOW'},experimental:{rsi14:rsi(closes),macd,macdHistogram:hist}}}
function scalpModel(base,f){if(!base?.market||!base?.btc?.latest||!f?.ok)return null;const m=base.market,p=base.btc.latest.p,rem=+base.timing?.seconds_remaining||300,ya=+m.yes_ask,na=+m.no_ask;if(!Number.isFinite(ya)||!Number.isFinite(na))return null;const mom=f.momentum.m1*.50+f.momentum.m3*.30+f.momentum.m5*.20,vr=Number.isFinite(+f.volume.ratio)?+f.volume.ratio:1,rv=Math.max(.00015,f.volatility.realized10||.001),noise=Math.max(8,p*rv*.10),strength=Math.abs(mom)/noise,dir=mom>=0?'YES':'NO',entry=dir==='YES'?ya:na,confidence=clamp(.50+.18*strength+.10*clamp((vr-.5)/.8,0,1)-(f.volatility.regime==='HIGH'?.05:0),.05,.92),move=clamp(.025+.055*strength+.025*clamp(vr,0,2),.03,.12),targetPrice=clamp(entry+move,.02,.98),stopPrice=clamp(entry-Math.max(.025,move*.6),.01,.97);const blockers=[];if(!(entry>.04&&entry<.96))blockers.push('contract price outside 4–96%');if(rem<15)blockers.push('less than 15 sec left');if(rem>840)blockers.push('more than 14 min left');if(Math.abs(mom)<1.5)blockers.push('momentum '+Math.abs(mom).toFixed(2)+' < 1.50');if(confidence<.52)blockers.push('confidence '+(confidence*100).toFixed(1)+'% < 52%');const qualifies=blockers.length===0;return{status:qualifies?'TRADE '+dir:'WATCH '+dir,side:qualifies?dir:null,direction:dir,confidence,entry,targetPrice,stopPrice,expectedHoldSeconds:strength>1.25?'20–45':'30–90',momentumScore:mom,volumeRatio:vr,timeLeft:Math.round(rem),blockers,reason:qualifies?'Short-term '+dir+' momentum setup':'Blocked: '+blockers.join(' · ')}}
function modelB(base,f){if(!base?.market||!base?.btc?.latest||!f?.ok)return null;const m=base.market,p=base.btc.latest.p,t=+m.target,rem=+base.timing?.seconds_remaining||300,ym=+m.yes_ask,nm=+m.no_ask;if(!Number.isFinite(t)||!Number.isFinite(ym)||!Number.isFinite(nm))return null;const mom=(f.momentum.m1*.5+f.momentum.m3*.25+f.momentum.m5*.15),volRatio=f.volume.ratio||1,volConfirm=clamp((volRatio-.65)/.9,0,1),rv=Math.max(.00015,f.volatility.realized10||.001),scale=Math.max(18,p*rv*Math.sqrt(Math.max(10,rem)/600)),z=(p-t+mom*(.55+.45*volConfirm))/scale,raw=1/(1+Math.exp(-1.55*z)),regimePenalty=f.volatility.regime==='HIGH'?.68:f.volatility.regime==='LOW'?.82:1,confidence=.5+(raw-.5)*regimePenalty,yp=clamp(.78*confidence+.22*ym,.03,.97),np=1-yp;const yes={side:'YES',probability:yp,market:ym,edge:yp-ym,mult:ym>0?1/ym:null},no={side:'NO',probability:np,market:nm,edge:np-nm,mult:nm>0?1/nm:null};const predicted=yp>=.5?yes:no,value=yes.edge>=no.edge?yes:no;const predEdge=predicted.edge,qualifies=predicted.probability>=.54&&predEdge>=.025&&rem>=20&&rem<=600&&predicted.market>.04&&predicted.market<.96;const best=qualifies?predicted:null;return{yes,no,predicted,value,best,bet:qualifies?predicted.side:'NO BET',inputs:{momentumScore:mom,volumeRatio:volRatio,volumeConfirmation:f.volume.confirmation,volatilityRegime:f.volatility.regime},status:qualifies?'PAPER SIGNAL':'WAIT'}}
// Estimates assume direct-member rounding, one full taker fill per leg, KXBTC15M multiplier 1.
function estimatedFee(price,count,side){if(!Number.isFinite(price)||price<0||price>1||count<=0)return null;const model=Math.ceil((.07*count*price*(1-price)-1e-10)*1e6)/1e6,revenue=(side==='buy'?-1:1)*count*price,change=Math.floor((revenue-model+1e-10)*1e4)/1e4;return Math.max(0,revenue-change)}
function paperSize(entry){if(!(entry>0&&entry<1))return 0;let n=Math.floor(5/entry);while(n>0&&n*entry+estimatedFee(entry,n,'buy')>5+1e-9)n--;return n}
function netEstimate(entry,exit,count){if(!Number.isFinite(entry)||!Number.isFinite(exit)||count<=0)return null;const entryFee=estimatedFee(entry,count,'buy'),exitFee=estimatedFee(exit,count,'sell'),cost=count*entry+entryFee,gross=count*(exit-entry),net=gross-entryFee-exitFee;return{contracts:count,entryFee,exitFee,cost,grossPnlDollars:gross,netPnlDollars:net,netReturnPct:cost>0?100*net/cost:null}}
function executionEstimate(m,sc){if(!sc)return null;const count=paperSize(sc.entry),bid=sc.direction==='YES'?m.yes_bid:m.no_bid;if(!count)return{contracts:0,warning:'No contract fits the $5 budget including estimated entry fee'};let breakEven=null;for(let i=Math.ceil(sc.entry*1000);i<=1000;i++){if(netEstimate(sc.entry,i/1000,count).netPnlDollars>1e-9){breakEven=i/1000;break}}const target=netEstimate(sc.entry,sc.targetPrice,count),immediate=bid!=null?netEstimate(sc.entry,bid,count):null;return{contracts:count,bid,spread:bid!=null?sc.entry-bid:null,breakEvenSellBid:breakEven,targetNetDollars:target?.netPnlDollars??null,immediateNetDollars:immediate?.netPnlDollars??null,entryCost:count*sc.entry+estimatedFee(sc.entry,count,'buy'),feeAssumption:'Estimated taker fees on both legs; multiplier 1; direct-member rounding; top quote fills assumed',warning:target&&target.netPnlDollars<=0?'Target does not cover estimated round-trip fees':null}}
function accountedTrade(t){const count=t.contracts??Math.floor(5/t.entry),x=netEstimate(t.entry,t.exit,count);if(!x)return{...t,won:null,accounting:'unknown'};return{...t,...x,grossPnlPct:(t.exit-t.entry)/t.entry,pnlPct:x.netReturnPct/100,won:x.netPnlDollars>1e-9,breakeven:Math.abs(x.netPnlDollars)<=1e-9,accounting:'estimated-net-taker',reconstructed:!t.contracts}}
function normalizeMarket(raw){if(!raw?.ticker)throw Error('Missing market for paper tracking');const price=(d,c)=>{const x=d??c;if(x==null||x==='')return null;const n=Number(x);return Number.isFinite(n)?(d!=null?n:n/100):null};return{...raw,target:raw.floor_strike??raw.strike??raw.target??null,close_time:raw.close_time||raw.expiration_time||raw.expected_expiration_time,yes_bid:price(raw.yes_bid_dollars,raw.yes_bid),yes_ask:price(raw.yes_ask_dollars,raw.yes_ask),no_bid:price(raw.no_bid_dollars,raw.no_bid),no_ask:price(raw.no_ask_dollars,raw.no_ask)}}
async function current(req,env,ctx){
 const stub=env.PRICE_HISTORY.get(env.PRICE_HISTORY.idFromName('btc-usd'));
 const [mr,sr,fr]=await Promise.all([
  stub.fetch('https://collector/market'),
  stub.fetch('https://collector/snapshot'),
  stub.fetch('https://collector/candle-features')
 ]);
 const mk=await mr.json(),btc=await sr.json(),f=await fr.json();
 if(mk.status!=='live'||!mk.market)return json({ok:true,version:VERSION,server_time:new Date().toISOString(),market_status:'waiting',status:'waiting',message:mk.reason||'Waiting for next BTC 15-minute market.',market:null,btc,features:f,scalp:null,timing:{ms_remaining:null,seconds_remaining:null}});
 const m=normalizeMarket(mk.market);
 let latest=btc?.latest||null;if(!latest&&f?.ok&&Number.isFinite(+f.last_close))latest={p:+f.last_close,t:Date.now(),source:'coinbase-candle-fallback'};
 const close=Date.parse(m.close_time),rem=Math.max(0,(close-Date.now())/1000),base={market:m,btc:{latest,points:btc?.points||[]},timing:{seconds_remaining:rem}};
 const scalp=scalpModel(base,f),b=modelB(base,f);if(scalp)scalp.execution=executionEstimate(m,scalp);
 const paper=await stub.fetch(new Request('https://collector/scalp-tick',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({market:m,scalp,modelB:b,base,features:f})}));
 if(!paper.ok)throw Error('Paper tracking failed: '+paper.status);
 return json({ok:true,version:VERSION,server_time:new Date().toISOString(),market_status:'live',status:'live',market:m,btc:{...btc,latest},timing:{ms_remaining:rem*1000,seconds_remaining:rem,final_60:rem>0&&rem<=60},features:f,scalp,ab_test:{modelB:b}});
}
export default{async scheduled(event,env,ctx){ctx.waitUntil(current(new Request('https://worker/api/current'),env,ctx))},async fetch(req,env,ctx){const u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{headers:cors});if(u.pathname==='/'||u.pathname==='/health')return json({ok:true,service:'btc15-api',version:VERSION,ab_test:true,model_b:'momentum + volume',volatility_filter:true,rsi_macd:'recorded only',scalp_mode:true,time:new Date().toISOString()});if(u.pathname==='/api/live-status')return authStatus(env);if(u.pathname==='/api/scalp-experiments')return env.PRICE_HISTORY.get(env.PRICE_HISTORY.idFromName('btc-usd')).fetch('https://do/scalp-experiments');if(u.pathname==='/api/scalp-performance')return env.PRICE_HISTORY.get(env.PRICE_HISTORY.idFromName('btc-usd')).fetch('https://do/scalp-performance');if(u.pathname==='/api/push/latest')return env.PRICE_HISTORY.get(env.PRICE_HISTORY.idFromName('btc-usd')).fetch('https://collector/latest-alert');if(u.pathname==='/api/push-health')return env.PRICE_HISTORY.get(env.PRICE_HISTORY.idFromName('btc-usd')).fetch('https://do/push-health');if(u.pathname==='/api/current')try{return await current(req,env,ctx)}catch(e){return json({ok:false,version:VERSION,error:String(e?.message||e)},502)}return v44.fetch(req,env,ctx)}};




const TRIALS=[{id:'control',label:'Current rules',minScore:0},{id:'score75',label:'Score ≥75%',minScore:.75},{id:'score90',label:'Score ≥90%',minScore:.90},{id:'late75',label:'≥75% · final 8 min',minScore:.75,maxSeconds:480},{id:'late90',label:'≥90% · final 8 min',minScore:.90,maxSeconds:480},{id:'execution90',label:'≥90% · spread ≤2¢ + net R/R ≥1',minScore:.90,executionFilter:true}];
function trialEligible(t,m,sc){if(!sc?.side||sc.confidence<t.minScore)return false;if(t.maxSeconds&&!(sc.timeLeft>=15&&sc.timeLeft<=t.maxSeconds))return false;if(t.executionFilter){const bid=sc.side==='YES'?m.yes_bid:m.no_bid,n=paperSize(sc.entry),reward=netEstimate(sc.entry,sc.targetPrice,n),risk=netEstimate(sc.entry,sc.stopPrice,n);if(!Number.isFinite(bid)||sc.entry-bid<0||sc.entry-bid>.02+1e-9||!reward||!risk||reward.netPnlDollars<=0||risk.netPnlDollars>=0||reward.netPnlDollars/(-risk.netPnlDollars)<1)return false}return true}
function trialStats(log){let net=0,peak=0,drawdown=0,gains=0,loss=0,wins=0,losses=0;for(const x of log){const p=x.netPnlDollars||0;net+=p;peak=Math.max(peak,net);drawdown=Math.max(drawdown,peak-net);if(p>1e-9){wins++;gains+=p}else if(p< -1e-9){losses++;loss-=p}}return{trades:log.length,wins,losses,winRate:log.length?wins/log.length:null,netDollars:net,maxDrawdownDollars:drawdown,profitFactor:loss?gains/loss:null,feesDollars:log.reduce((a,x)=>a+x.entryFee+x.exitFee,0),history:log.slice().reverse()}}

export function signalDataHealth(m,sc,base,f){const btc=base?.btc?.latest?.p;let reason=null;if(!sc){if(!m?.ticker)reason='Market data unavailable';else if(!base?.btc?.latest)reason='BTC price unavailable';else if(!f?.ok)reason=f?.error||'Candle features unavailable';else reason='Scalp calculation returned no signal'}return{at:Date.now(),ticker:m?.ticker||null,available:!!sc,reason,btcPriceAvailable:Number.isFinite(btc),candlesOk:f?.ok===true,candleCount:f?.candles??null,featureError:f?.error||null,source:f?.source??null,fallbackReason:f?.fallbackReason??null,cacheAgeMs:f?.cacheAgeMs??null,retryAt:f?.retryAt??null}}
